import { IMAGES } from './images';

// ─── STORIES ─────────────────────────────────────────────────────────────────
export const STORIES = [
  {
    id: 1,
    number: '01',
    tag: 'Origin Story',
    title: 'The Day I Chose Fear',
    subtitle: 'First Solo Travel',
    image: IMAGES.airportSelfie,
    color: '#7c3aed',
    location: 'Algeria',
    excerpt: "No plan. No experience. Just a bag, a ticket, and the decision to stop waiting.",
    body: [
      "Everyone told me it was a bad idea. Travel alone? From Algeria? Where would I go? Who would I know?",
      "I didn't have answers. I just had the unbearable feeling that staying would be worse.",
      "That first journey was clumsy, anxious, and completely transformative. I got lost. I missed buses. I slept in places I'd never have chosen with more experience.",
      "And I loved every second of it. Because fear, when you move through it, becomes something else entirely.",
    ],
  },
  {
    id: 2,
    number: '02',
    tag: 'Budget Travel',
    title: 'Everything. Zero Money.',
    subtitle: 'Hitchhiking & Free Stays',
    image: IMAGES.budgetRoom,
    color: '#d97706',
    location: 'Across Europe',
    excerpt: "Hitchhiking across continents, sleeping on strangers' couches. Connection over comfort, every time.",
    body: [
      "There's a version of travel that costs nothing except pride. You ask for rides. You sleep on couches. You eat what people offer.",
      "People think budget travel means suffering. It's the opposite. It forces connection.",
      "Every host taught me something. Every hitchhiked kilometer had a story behind the windshield.",
      "Money doesn't buy experience. Openness does.",
    ],
  },
  {
    id: 3,
    number: '03',
    tag: 'Africa',
    title: 'Living with the Maasai',
    subtitle: 'Kenya & Tanzania',
    image: IMAGES.tentMarket,
    color: '#dc2626',
    location: 'East Africa',
    excerpt: "Three days. No signal, no running water. A complete reset of what the word 'enough' actually means.",
    body: [
      "The Maasai don't measure wealth in money. They measure it in cattle, in community, in the depth of knowledge passed through generations.",
      "I arrived as a visitor. I left questioning everything I'd built my life around.",
      "They welcomed me into their world without hesitation. A stranger from a continent they'd never visited, who spoke none of their language.",
      "I've never felt more welcomed. Or more humbled.",
    ],
  },
  {
    id: 4,
    number: '04',
    tag: 'Ancient Living',
    title: 'The Cave Was Home',
    subtitle: 'Cavemen Experience',
    image: IMAGES.caveInterior,
    color: '#059669',
    location: 'Undisclosed',
    excerpt: "Stone walls. No electricity. Cooking over fire. Three days living exactly as humans did for ten thousand years.",
    body: [
      "Some people build smart homes. This family had carved their home from the earth itself, the same way their ancestors had ten thousand years ago.",
      "At first it felt like a step backward. By the second day, it felt like the most rational way to live.",
      "The silence was absolute. The stars were blinding. The food, cooked over wood and flame, was some of the best I've ever tasted.",
      "We've complicated everything that was once simple.",
    ],
  },
  {
    id: 5,
    number: '05',
    tag: 'Northern Lights',
    title: 'The Night the Sky Caught Fire',
    subtitle: 'Aurora Borealis',
    image: IMAGES.auroraArms,
    color: '#0891b2',
    location: 'Lapland, Finland',
    excerpt: "Minus twenty degrees, completely alone. Then the sky erupted in green and violet. The most spectacular thing I've ever seen.",
    body: [
      "My local host, a Finnish man of sixty who spoke in sentences no longer than four words, drove me thirty kilometers from the nearest town and left me in the dark.",
      '"Wait," he said. And drove away.',
      "Forty minutes later, the sky erupted. Green and violet light, moving like something alive, like the universe breathing.",
      "I cried. I don't know when it started. I just know that when he came back, I wasn't the same person he'd dropped off.",
    ],
  },
  {
    id: 6,
    number: '06',
    tag: 'Danger',
    title: "Uganda. I Almost Didn't Come Back.",
    subtitle: 'Real Danger Story',
    image: IMAGES.ugandaHospital,
    color: '#be123c',
    location: 'Uganda',
    excerpt: "There are moments where your life depends on your next decision. Uganda gave me one of those moments.",
    body: [
      "There are moments in travel where you understand, with absolute clarity, that your life depends on the next decision you make.",
      "Uganda gave me one of those moments.",
      "I ended up in a hospital bed in a city where I knew no one, with no working phone, and a situation I couldn't explain in the local language.",
      "What followed was an act of human kindness so overwhelming that I still can't talk about it without my voice breaking.",
      "I made it back. Not alone.",
    ],
  },
];

// ─── COUNTRIES BY CONTINENT ───────────────────────────────────────────────────
export const CONTINENTS = [
  {
    id: 'europe',
    name: 'Europe',
    emoji: '🇪🇺',
    color: '#6366f1',
    countries: [
      { name: 'Austria',                flag: '🇦🇹' },
      { name: 'Belgium',                flag: '🇧🇪' },
      { name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
      { name: 'Bulgaria',               flag: '🇧🇬' },
      { name: 'Croatia',                flag: '🇭🇷' },
      { name: 'Denmark',                flag: '🇩🇰' },
      { name: 'Finland',                flag: '🇫🇮' },
      { name: 'France',                 flag: '🇫🇷' },
      { name: 'Germany',                flag: '🇩🇪' },
      { name: 'Greece',                 flag: '🇬🇷' },
      { name: 'Hungary',                flag: '🇭🇺' },
      { name: 'Italy',                  flag: '🇮🇹' },
      { name: 'Liechtenstein',          flag: '🇱🇮' },
      { name: 'Luxembourg',             flag: '🇱🇺' },
      { name: 'Netherlands',            flag: '🇳🇱' },
      { name: 'Norway',                 flag: '🇳🇴' },
      { name: 'Poland',                 flag: '🇵🇱' },
      { name: 'Portugal',               flag: '🇵🇹' },
      { name: 'Romania',                flag: '🇷🇴' },
      { name: 'Slovakia',               flag: '🇸🇰' },
      { name: 'Slovenia',               flag: '🇸🇮' },
      { name: 'Spain',                  flag: '🇪🇸' },
      { name: 'Sweden',                 flag: '🇸🇪' },
      { name: 'Switzerland',            flag: '🇨🇭' },
    ],
  },
  {
    id: 'africa',
    name: 'Africa',
    emoji: '🌍',
    color: '#dc2626',
    countries: [
      { name: 'Algeria',  flag: '🇩🇿' },
      { name: 'Botswana', flag: '🇧🇼' },
      { name: 'Kenya',    flag: '🇰🇪' },
      { name: 'Morocco',  flag: '🇲🇦' },
      { name: 'Rwanda',   flag: '🇷🇼' },
      { name: 'Tanzania', flag: '🇹🇿' },
      { name: 'Tunisia',  flag: '🇹🇳' },
      { name: 'Uganda',   flag: '🇺🇬' },
      { name: 'Zambia',   flag: '🇿🇲' },
      { name: 'Zimbabwe', flag: '🇿🇼' },
    ],
  },
  {
    id: 'middleeast',
    name: 'Middle East',
    emoji: '🌙',
    color: '#d97706',
    countries: [
      { name: 'Qatar',        flag: '🇶🇦' },
      { name: 'Saudi Arabia', flag: '🇸🇦' },
      { name: 'Turkey',       flag: '🇹🇷' },
    ],
  },
  {
    id: 'asia',
    name: 'Asia',
    emoji: '🌏',
    color: '#0891b2',
    countries: [
      { name: 'China',     flag: '🇨🇳' },
      { name: 'Indonesia', flag: '🇮🇩' },
      { name: 'Malaysia',  flag: '🇲🇾' },
      { name: 'Thailand',  flag: '🇹🇭' },
    ],
  },
];

// ─── GALLERY ITEMS ────────────────────────────────────────────────────────────
export const GALLERY_ITEMS = [
  { id: 1,  src: IMAGES.auroraArms,     category: 'nature',     location: 'Lapland, Finland',    title: 'Aurora Borealis',     aspect: 'portrait'  },
  { id: 2,  src: IMAGES.auroraRoad,     category: 'nature',     location: 'Scandinavia',          title: 'Road to the Lights',  aspect: 'landscape' },
  { id: 3,  src: IMAGES.fjord1,         category: 'nature',     location: 'Norway',               title: 'Into the Fjord',      aspect: 'portrait'  },
  { id: 4,  src: IMAGES.fjord2,         category: 'nature',     location: 'Norway',               title: 'Canyon Waters',       aspect: 'portrait'  },
  { id: 5,  src: IMAGES.waterfall,      category: 'nature',     location: 'Unknown',              title: 'The Falls',           aspect: 'portrait'  },
  { id: 6,  src: IMAGES.desertSand,     category: 'nature',     location: 'Sahara Desert',        title: 'Sea of Sand',         aspect: 'portrait'  },
  { id: 7,  src: IMAGES.viennaGold,     category: 'cities',     location: 'Vienna, Austria',      title: 'Golden Vienna',       aspect: 'portrait'  },
  { id: 8,  src: IMAGES.viennaCathedral,category: 'cities',     location: 'Vienna, Austria',      title: 'Stephansdom',         aspect: 'portrait'  },
  { id: 9,  src: IMAGES.copenhagen,     category: 'cities',     location: 'Copenhagen, Denmark',  title: 'Nyhavn Harbor',       aspect: 'landscape' },
  { id: 10, src: IMAGES.colorBuildings, category: 'cities',     location: 'Europe',               title: 'Painted Streets',     aspect: 'landscape' },
  { id: 11, src: IMAGES.colorMarket,    category: 'cities',     location: 'Europe',               title: 'Market Day',          aspect: 'landscape' },
  { id: 12, src: IMAGES.cityNight,      category: 'cities',     location: 'Europe',               title: 'City After Dark',     aspect: 'landscape' },
  { id: 13, src: IMAGES.mecca1,         category: 'culture',    location: 'Mecca, Saudi Arabia',  title: 'The Pilgrimage',      aspect: 'portrait'  },
  { id: 14, src: IMAGES.mecca2,         category: 'culture',    location: 'Mecca, Saudi Arabia',  title: 'The Sacred House',    aspect: 'landscape' },
  { id: 15, src: IMAGES.desertArab,     category: 'culture',    location: 'Middle East',          title: 'Desert Traditions',   aspect: 'portrait'  },
  { id: 16, src: IMAGES.reindeer,       category: 'culture',    location: 'Lapland, Finland',     title: 'Arctic Friends',      aspect: 'landscape' },
  { id: 17, src: IMAGES.hotAirBalloon,  category: 'adventures', location: 'Qatar',                title: 'Above It All',        aspect: 'portrait'  },
  { id: 18, src: IMAGES.desertHelmet,   category: 'adventures', location: 'Desert',               title: 'Dust & Speed',        aspect: 'portrait'  },
  { id: 19, src: IMAGES.stadium1,       category: 'adventures', location: 'Qatar',                title: 'World Cup Moments',   aspect: 'landscape' },
  { id: 20, src: IMAGES.airplane2,      category: 'adventures', location: 'Maho Beach',           title: 'Jet Blast',           aspect: 'landscape' },
];

// ─── SOCIAL STATS ─────────────────────────────────────────────────────────────
export const STATS = [
  { value: 1000000, suffix: '+', label: 'Total Followers', short: '1M+' },
  { value: 50,      suffix: '+', label: 'Countries',       short: '50+' },
  { value: 6,       suffix: '',  label: 'Continents',      short: '6'   },
  { value: 100,     suffix: 'M+',label: 'Total Views',     short: '100M+'},
];

// ─── NAV LINKS ────────────────────────────────────────────────────────────────
export const NAV_LINKS = [
  { href: '#about',   label: 'About'   },
  { href: '#travels', label: 'Travels' },
  { href: '#stories', label: 'Stories' },
  { href: '#collab',  label: 'Collab'  },
];

// ─── SOCIAL LINKS ────────────────────────────────────────────────────────────
export const SOCIALS = [
  { name: 'Instagram',      handle: '@RanzoDz',  url: 'https://www.instagram.com/ranzodz',                                   abbr: 'IG', color: '#E1306C' },
  { name: 'YouTube',        handle: '@RanzoDz',  url: 'https://www.youtube.com/c/ranzodz',                                   abbr: 'YT', color: '#FF0000' },
  { name: 'TikTok',         handle: '@RanzoDz',  url: 'https://www.tiktok.com/@ranzodz',                                    abbr: 'TK', color: '#010101' },
  { name: 'Kick',           handle: '@RanzoDz',  url: 'https://kick.com/ranzodz',                                           abbr: 'KC', color: '#53FC18' },
  { name: 'Facebook',       handle: '@RanzoDz',  url: 'https://www.facebook.com/ranzodz',                                   abbr: 'FB', color: '#1877F2' },
  { name: 'Facebook 2',     handle: '@RanzoDZA', url: 'https://www.facebook.com/RanzoDZA',                                  abbr: 'FB', color: '#1877F2' },
  { name: 'YouTube Gaming', handle: '@RanzoDz',  url: 'https://www.youtube.com/channel/UCY8BV1FLuJWY4aV6QSaQ35Q/featured', abbr: 'YG', color: '#FF0000' },
  { name: 'Donate',         handle: 'Streamlabs', url: 'https://streamlabs.com/ranzolite/tip',                              abbr: 'TIP', color: '#80F5D2' },
  { name: 'PayPal',         handle: 'Donate',    url: 'https://www.paypal.com/paypalme/AbdullahKhalfi',                     abbr: 'PP', color: '#003087' },
];

// ─── ALL LINKS (for footer / link tree) ──────────────────────────────────────
export const ALL_LINKS = [
  { name: 'Instagram', url: 'https://www.instagram.com/ranzodz' },
  { name: 'YouTube', url: 'https://www.youtube.com/c/ranzodz' },
  { name: 'TikTok', url: 'https://www.tiktok.com/@ranzodz' },
  { name: 'Kick', url: 'https://kick.com/ranzodz' },
  { name: 'Facebook', url: 'https://www.facebook.com/ranzodz' },
  { name: 'YouTube Gaming', url: 'https://www.youtube.com/channel/UCY8BV1FLuJWY4aV6QSaQ35Q/featured' },
  { name: 'Donate', url: 'https://streamlabs.com/ranzolite/tip' },
  { name: 'PayPal', url: 'https://www.paypal.com/paypalme/AbdullahKhalfi' },
];

// ─── TRAVEL APPS ─────────────────────────────────────────────────────────────
export const TRAVEL_APPS = [
  {
    name: 'Skyscanner',
    category: 'Flights',
    desc: 'Find the cheapest flights worldwide',
    url: 'https://www.skyscanner.com',
    emoji: '✈️',
    color: '#0770e3',
  },
  {
    name: 'Booking.com',
    category: 'Hotels',
    desc: 'Best hotel deals and reviews',
    url: 'https://www.booking.com',
    emoji: '🏨',
    color: '#003580',
  },
  {
    name: 'Hostelworld',
    category: 'Hostels',
    desc: 'Budget-friendly hostels globally',
    url: 'https://www.hostelworld.com',
    emoji: '🛏️',
    color: '#f47b20',
  },
  {
    name: 'Couchsurfing',
    category: 'Free Stays',
    desc: 'Stay with locals for free',
    url: 'https://www.couchsurfing.com',
    emoji: '🛋️',
    color: '#e0534f',
  },
  {
    name: 'GetYourGuide',
    category: 'Activities',
    desc: 'Tours, attractions and experiences',
    url: 'https://www.getyourguide.com',
    emoji: '🎯',
    color: '#ff5533',
  },
  {
    name: 'Rome2Rio',
    category: 'Transport',
    desc: 'Get from A to B anywhere in the world',
    url: 'https://www.rome2rio.com',
    emoji: '🚂',
    color: '#00b0ff',
  },
  {
    name: 'MobiMatter',
    category: 'eSIM',
    desc: 'Affordable eSIM for international travel',
    url: 'https://www.mobimatter.com',
    emoji: '📱',
    color: '#4caf50',
  },
  {
    name: 'XE Currency',
    category: 'Converter',
    desc: 'Real-time currency converter',
    url: 'https://www.xe.com',
    emoji: '💱',
    color: '#00458b',
  },
  {
    name: 'Numbeo',
    category: 'Cost of Living',
    desc: 'Compare cost of living worldwide',
    url: 'https://www.numbeo.com',
    emoji: '📊',
    color: '#2e7d32',
  },
];
